### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by redman9** [baidu-ife/ife#131]
你好，我是去年毕业的学生，但是对前端很有兴趣，这一段也在学习。然后我看到报名条件对于毕业年限有限制，我想问下是否有机会？另外，如果没有的话，是否有其他途径应聘一个实习生职位？谢谢

**Comment by diysimon** [comment]
百度只能招在校同学作为实习生。后续可能会针对非在校生做类似的活动，多关注我们微博，谢谢
