### ISSUE TITLE
初级班 task0001 任务提交issue

### ISSUE THREAD

**Issue by sepmoyoung** [baidu-ife/ife#777]
https://github.com/sepmoyoung/ife/tree/master/task/task0001

**Comment by CiSplus** [comment]
https://github.com/CiSplus/ife/tree/master/task/task0001/work/CiSplus
感谢~

**Comment by diysimon** [comment]
sepmoyoung review done，见邮箱

**Comment by diysimon** [comment]
CiSplus review done，见邮箱
