### ISSUE TITLE
可以在这里找队友嘛？

### ISSUE THREAD

**Issue by JoyHwong** [baidu-ife/ife#870]
前端小白一枚，爱看书，看到这个的，有人愿意一起组队嘛。

**Comment by zjhnys** [comment]
同求组队。本科计算机，有一定的前端基础，目前自学中

**Comment by lsl233** [comment]
+1

**Comment by Lovin0730** [comment]
一般一队要多少人呀

**Comment by JoyHwong** [comment]
组队的好像是3到5个人

**Comment by bettering** [comment]
自学前端，html与css学完，有两个小项目，javascript学到面向对象，求组队。

**Comment by menhal** [comment]
什么情况? 项目不是已经结束了吗

**Comment by LynnWei** [comment]
俺也是目前UI自学前端已学完css h5，临摹了几个静态网页，正在学js和其他知识，我也要一起组队0.0（真诚的眼神.jpg）

**Comment by menhal** [comment]
本人前端工作一年, 想继续深造一下. 求组队QQ:124796494

**Comment by bettering** [comment]
q群。百度前端学院信息交流群。515562855

**Comment by JoyHwong** [comment]
组队求加QQ:961165750

**Comment by LinesWan** [comment]
组队请加群：543132025

**Comment by XeCtvi** [comment]
组队请加 qq 635189253
本人有一定基础，缺乏实际项目操作。一起学习哈。我这有一个小伙伴了，加我一加加两人。[脸红]

**Comment by momeakl** [comment]
来组队吧=￣ω￣=   队名： 前端科学家  欢迎加入嘞

**Comment by SunaChen** [comment]
一年前端经验，有没有一起的？？
